version: "2"

services:
  mariadb:
    image: mariadb:latest
    restart: always
    networks:
      - network1
    volumes:
      - mariadb:/var/lib/mysql
      - ./omeka.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: blabla
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka

  pma:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    networks:
      - network1
    ports:
      - "8080:80"
    links:
      - mariadb:db

  omeka:
    depends_on:
      - mariadb
      - certbot
    build: .
    restart: always
    networks:
      - network1
    links:
      - mariadb:db
    volumes:
      - omeka:/var/www/html/volume
      - $PWD/files:/var/www/html/files 

  certbot:
    image: linuxserver/letsencrypt
    ports:
      - "443:443"
      - "80:80"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=situatedviews.axismaps.io
      - VALIDATION=http
    volumes:
      - letsencrypt:/config

volumes:
  mariadb:
  omeka:
  letsencrypt: 

networks:
  network1:
