version: "2"

services:
  mariadb:
    image: mariadb:latest
    restart: always
    networks:
      - network1
    volumes:
      - mariadb:/var/lib/mysql
      - ./omeka.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: blabla
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka

  pma:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    networks:
      - network1
    ports:
      - "8080:80"
    links:
      - mariadb:db

  omeka:
    depends_on:
      - mariadb
    build: .
    restart: always
    networks:
      - network1
    ports:
      - "80:80"
    links:
      - mariadb:db
    volumes:
      - omeka:/var/www/html/volume
      - $PWD/files:/var/www/html/files
      - letsencrypt_challenges:/var/www/html/.well-known/acme-challenge/

  certbot:
    depends_on:
      - omeka
    image: blacklabelops/letsencrypt
    networks:
      - network1
    volumes:
      - letsencrypt_certificates:/etc/letsencrypt
      - letsencrypt_challenges:/var/www/letsencrypt

volumes:
  mariadb:
  omeka:
  letsencrypt_certificates:
  letsencrypt_challenges:

networks:
  network1:
